#!/usr/bin/env node
/*
 * Build Rebound Relay (Figma) into a single self-contained plugin under dist/.
 *
 * Figma needs one bundled main script and one inlined UI file, and no runtime
 * npm. We keep the project buildless by simply concatenating the shared IR libs
 * with the plugin source (no transpiler), and inlining the UI css/js into the
 * html. Output: dist/main.js + dist/ui.html, referenced by manifest.json.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const sharedLib = path.join(repo, 'shared', 'lib');
const src = path.join(here, 'src');
const dist = path.join(here, 'dist');

function read(p) { return fs.readFileSync(p, 'utf8'); }

fs.mkdirSync(dist, { recursive: true });

// Bundle the sandbox entry: shared libs first (they define the globals the IR
// builder uses), then the builder, then the entry. A semicolon between files
// guards against any accidental ASI hazard at a boundary.
const mainBundle = [
  '/* Rebound Relay (Figma) - generated by build.mjs. Do not edit dist/. */',
  read(path.join(sharedLib, 'normalize.js')),
  read(path.join(sharedLib, 'bezier.js')),
  read(path.join(src, 'ir-build.js')),
  read(path.join(src, 'main.js'))
].join('\n;\n');
fs.writeFileSync(path.join(dist, 'main.js'), mainBundle);

// Inline the UI css + js into the html template.
let html = read(path.join(src, 'ui.html'));
html = html.replace('/*__CSS__*/', read(path.join(src, 'ui.css')));
html = html.replace('/*__JS__*/', read(path.join(src, 'ui.js')));
fs.writeFileSync(path.join(dist, 'ui.html'), html);

console.log('Built Rebound Relay -> ' + path.relative(repo, dist));
